aws:
  s3:
    region: us-east-1
    # When using AWS, the library will use one of the available
    # credential sources described in the documentation.
    accessKeyId:
    secretAccessKey:
    bucket:
    endpoint:



